"""empty message

Revision ID: 23bfef078b06
Revises: 47c81a0d0be7
Create Date: 2014-06-22 18:04:41.935383

"""

# revision identifiers, used by Alembic.
revision = '23bfef078b06'
down_revision = '47c81a0d0be7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('winrate_interval', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('winrate_map', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'winrate_map')
    op.drop_column('user', 'winrate_interval')
    ### end Alembic commands ###
