"""empty message

Revision ID: 50e77b6e7331
Revises: 9e520de441f
Create Date: 2014-11-17 13:21:23.705195

"""

# revision identifiers, used by Alembic.
revision = '50e77b6e7331'
down_revision = '9e520de441f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ts3_longest_stretch', sa.Interval(), nullable=True))
    op.add_column('user', sa.Column('ts3_stretch_award_time', sa.DateTime(), nullable=True))
    op.drop_column('user', u'random_heroes')
    op.drop_column('user', u'ts3_connections')
    op.drop_column('user', u'az_completions')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(u'az_completions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column(u'ts3_connections', mysql.TEXT(), nullable=True))
    op.add_column('user', sa.Column(u'random_heroes', mysql.TEXT(), nullable=True))
    op.drop_column('user', 'ts3_stretch_award_time')
    op.drop_column('user', 'ts3_longest_stretch')
    ### end Alembic commands ###
