"""empty message

Revision ID: 577491697958
Revises: 1c90e0fd276a
Create Date: 2014-09-12 14:12:53.473274

"""

# revision identifiers, used by Alembic.
revision = '577491697958'
down_revision = '1c90e0fd276a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hitbox', sa.String(length=60), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hitbox')
    ### end Alembic commands ###
