"""empty message

Revision ID: 9e520de441f
Revises: 577491697958
Create Date: 2014-09-12 14:24:45.626386

"""

# revision identifiers, used by Alembic.
revision = '9e520de441f'
down_revision = '577491697958'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
